title:              데이식스 플레이
email:              my@day6.kr
description:        세상에서 가장 빠르게 데이식스의 음악을 담을 수 있는 데이식스 플레이에서 순식간에 수많은 데이식스의 음악을 담아보세요.
author:             데이식스 음원자료
baseurl:            ""
url:                "https://day6.kr"
enforce_ssl:        "www.day6.kr"

# Social Profiles
twitter_username:   DAY6MusicData
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-188229767-1 # out your google-analytics code

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           10
paginate_path:      "/playlists/page:num"
plugins:
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
